### ISSUE TITLE
Operators used in the Half and Full Adder Modules

### ISSUE THREAD

**Issue by CoreSync-Innovations** [CoreSync-Innovations/Diploma-1day-Workshop#3]
In both the codes, the bitwise operators, `& and ^`  have been used in conjunction with arithmetic operator ` + ` . Is this the best way to do it? Revisit and refine

**Comment by RadioactiveScandium** [comment]
@mayureshpiske  - There are three possible agents here :

```
                  1. Arithmetic
                  2. Logical
                  3. Bitwise
```

Which operator should we choose?

**Comment by CoreSync-Innovations** [comment]
Both the codes have been fixed. Commit id on 14th August : `789191d112fac7a5abc38f1d9826adc904946d51`
